#!/bin/bash

set -e

yarn build
node --enable-source-maps modules/build-raptor/dist/src/main.js build

RESULT_FILE=$(mktemp)

npx monocrate@0.15.0 \
  --packages=modules/build-raptor --packages=modules/build-raptor-jest-reporter --packages=modules/build-raptor-api \
  --bump minor \
  --max \
  --output-json "$RESULT_FILE"

NEXT_VERSION=$(node -p "JSON.parse(require('fs').readFileSync('$RESULT_FILE', 'utf8')).resolvedVersion")
echo "published version: $NEXT_VERSION"

# Tag and push
T="published@$NEXT_VERSION"
echo "tagging $T"
git tag "$T"
git push --tags
