#!/bin/bash

set -e

yarn build
node --enable-source-maps modules/build-raptor/dist/src/main.js build

RESULT_FILE=$(mktemp)
echo RESULT_FILE=$RESULT_FILE

npx monocrate@0.17.0 \
  --packages=modules/build-raptor --packages=modules/build-raptor-jest-reporter --packages=modules/build-raptor-api \
  --bump minor \
  --max \
  --report="${RESULT_FILE}"

NEXT_VERSION=$(node -p "fs.readFileSync(\"$RESULT_FILE\").toString().trim()")

echo "published version: $NEXT_VERSION"

# Tag and push
T="published@$NEXT_VERSION"
echo "tagging $T"
git tag "$T"
git push --tags
